=== it-helpers/it-wallet-helpers/docs/schemes/jwt_entity-configuration_eid_provider.json
{
    "$id": "https://example.com/entity-configuration_eid_provider.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "entity configuration ieD Provider",
    "type": "object",
    "properties":{
        "exp": "1649610249",
        "iat": "1649437449",
        "iss": "https://it-wallet-eid-provider.example.it",
        "sub": "https://it-wallet-eid-provider.example.it",
        "jwks": {
            "keys": [
                {
                    "kty": "RSA",
                    "use": "sig",
                    "n": "w4wEivQmGFZ04_ucwCqDihZcygppZfPa7KYA2D88mZz_JHLPsyip7LqSloB6xln1gp1UQREGiutv10FHvn3TXVj5P6pj7xp88nWZVaRpGKeGXgWxzzB4DcPv4Wykk5p2kkeezMYsspFM22YyVVD0tWBKbaJyFqEI60QrtXws1jXOv5KGX8DW0BryjNB5x1_QHWrASYzEPaybApgweioWWdxVjzkinLRX_G93xqU_3973vd_ysrfv5hSh5R5AiBP5S1iuC1MA2Ftv98etbv8iQ_zKy-Epk8JPI9VS9qqfgx0kKUjtaTSaT_TNtanv-bye8WDXE0-ik6DOScfEMS00Ww",
                    "e": "AQAB",
                    "kid": "eNN-g5i6CnLKcltQBp6abbioGMbzM6muW3vuxw6uh88"
                }
            ]
        },
        "authority_hints": [
            "https://superior-entity.example.org/federation"
        ],
        "metadata": {
            "federation_entity": {
                "organization_name": "Istituto Poligrafico e Zecca dello Stato",
                "homepage_uri": "https://it-wallet-eid-provider.example.it",
                "policy_uri": "https://it-wallet-eid-provider.example.it/privacy_policy",
                "tos_uri": "https://it-wallet-eid-provider.example.it/info_policy",
                "logo_uri": "https://it-wallet-eid-provider.example.it/logo.svg",
                "contacts": [
                    "protocollo@pec.ipzs.it"
                ]
            },
            "oauth_authorization_server": {
                "authorization_endpoint": "https://it-wallet-eid-provider.example.it/authorization",
                "pushed_authorization_request_endpoint": "https://it-wallet-eid-provider.example.it/as/par",
                "dpop_signing_alg_values_supported": [
                    "ES256",
                    "ES512"
                ],
                "token_endpoint": "https://it-wallet-eid-provider.example.it/token",
                "client_registration_types_supported": [
                    "automatic"
                ],
                "code_challenge_methods_supported": [
                    "S256"
                ],
                "authorization_details_types_supported": [
                    "openid_credential"
                ],
                "acr_values_supported": [
                    "https://www.spid.gov.it/SpidL2",
                    "https://www.spid.gov.it/SpidL3"
                ],
                "grant_types_supported": [
                    "authorization_code"
                ],
                "issuer": "https://it-wallet-eid-provider.example.it",
                "jwks": {
                    "keys": [
                        {
                            "crv": "P-256",
                            "kty": "EC",
                            "x": "newK5qDYMekrCPPO-yEYTdJVWJMTzasMavt2vm1Mb-A",
                            "y": "VizXaLO6dzeesZPxfpGZabTK3cTXtBUbIiQpmiYRtSE",
                            "kid": "ff0bded045fe63fe5d1d64dd83b567e0"
                        }
                    ]
                },
                "scopes_supported": [
                    "PersonIdentificationData"
                ],
                "request_parameter_supported": true,
                "request_uri_parameter_supported": false,
                "response_types_supported": [
                    "code"
                ],
                "subject_types_supported": [
                    "pairwise"
                ],
                "token_endpoint_auth_methods_supported": [
                    "attest_jwt_client_auth"
                ],
                "token_endpoint_auth_signing_alg_values_supported": [
                    "ES256",
                    "ES384",
                    "ES512"
                ],
                "request_object_signing_alg_values_supported": [
                    "ES256",
                    "ES384",
                    "ES512"
                ]
            },
            "openid_credential_issuer": {
                "credential_issuer": "https://it-wallet-eid-provider.example.it",
                "credential_endpoint": "https://it-wallet-eid-provider.example.it/credential",
                "revocation_endpoint": "https://it-wallet-eid-provider.example.it/revoke",
                "status_attestation_endpoint": "https://it-wallet-eid-provider.example.it/status",
                "dpop_signing_alg_values_supported": [
                    "ES256",
                    "ES512"
                ],
                "display": [
                    {
                        "name": "PID Provider Italiano di esempio",
                        "locale": "it-IT"
                    },
                    {
                        "name": "Example PID Provider",
                        "locale": "en-US",
                        "logo": {
                            "url": "https://it-wallet-eid-provider.example.it/public/logo.svg",
                            "alt_text": "logo di questo PID Provider"
                        }
                    }
                ],
                "jwks": {
                    "keys": [
                        {
                            "crv": "P-256",
                            "kty": "EC",
                            "x": "newK5qDYMekrCPPO-yEYTdJVWJMTzasMavt2vm1Mb-A",
                            "y": "VizXaLO6dzeesZPxfpGZabTK3cTXtBUbIiQpmiYRtSE",
                            "kid": "ff0bded045fe63fe5d1d64dd83b567e0"
                        }
                    ]
                },
                "credential_configurations_supported": [
                    {
                        "format": "vc+sd-jwt",
                        "cryptographic_binding_methods_supported": [
                            "jwk"
                        ],
                        "credential_signing_alg_values_supported": [
                            "ES256",
                            "ES384",
                            "ES512"
                        ],
                        "proof_types_supported": {
                            "jwt": {
                                "proof_signing_alg_values_supported": [
                                    "ES256"
                                ]
                            }
                        },
                        "display": [
                            {
                                "name": "PID Italiano di esempio",
                                "locale": "it-IT",
                                "logo": {
                                    "url": "https://it-wallet-eid-provider.example.it/public/logo.svg",
                                    "alt_text": "logo di questa Credenziale"
                                },
                                "background_color": "#12107c",
                                "text_color": "#FFFFFF"
                            },
                            {
                                "name": "Example Italian PID",
                                "locale": "en-US",
                                "logo": {
                                    "url": "https://it-wallet-eid-provider.example.it/public/logo.svg",
                                    "alt_text": "The logo of this credential"
                                },
                                "background_color": "#12107c",
                                "text_color": "#FFFFFF"
                            }
                        ],
                        "credential_definition": {
                            "type": [
                                "PersonIdentificationData"
                            ],
                            "verification": {
                                "trust_framework": "eidas",
                                "assurance_level": "high",
                                "evidence": [
                                    {
                                        "type": "electronic_record",
                                        "record": {
                                            "type": "https://eudi.wallet.cie.gov.it",
                                            "source": {
                                                "organization_name": "Ministero dell'Interno",
                                                "organization_id": "urn:eudi:it:organization_id:ipa_code:m_it",
                                                "country_code": "IT"
                                            }
                                        }
                                    }
                                ]
                            },
                            "credentialSubject": {
                                "given_name": {
                                    "mandatory": true,
                                    "display": [
                                        {
                                            "name": "Current First Name",
                                            "locale": "en-US"
                                        },
                                        {
                                            "name": "Nome",
                                            "locale": "it-IT"
                                        }
                                    ]
                                },
                                "family_name": {
                                    "mandatory": true,
                                    "display": [
                                        {
                                            "name": "Current Family Name",
                                            "locale": "en-US"
                                        },
                                        {
                                            "name": "Cognome",
                                            "locale": "it-IT"
                                        }
                                    ]
                                },
                                "birth_date": {
                                    "mandatory": true,
                                    "display": [
                                        {
                                            "name": "Date of Birth",
                                            "locale": "en-US"
                                        },
                                        {
                                            "name": "Data di Nascita",
                                            "locale": "it-IT"
                                        }
                                    ]
                                },
                                "unique_id": {
                                    "mandatory": true,
                                    "display": [
                                        {
                                            "name": "Unique Identifier",
                                            "locale": "en-US"
                                        },
                                        {
                                            "name": "Identificativo univoco",
                                            "locale": "it-IT"
                                        }
                                    ]
                                },
                                "tax_id_code": {
                                    "mandatory": true,
                                    "display": [
                                        {
                                            "name": "Tax Id Number",
                                            "locale": "en-US"
                                        },
                                        {
                                            "name": "Codice Fiscale",
                                            "locale": "it-IT"
                                        }
                                    ]
                                }
                            }
                        }
                    }
                ]
            }
        }
    }
}

=== it-helpers/it-wallet-helpers/docs/schemes/examples/eid-ec.json
{
    "iss": "https://eid-provider.wallet.ipzs.it",
    "sub": "https://eid-provider.wallet.ipzs.it",
    "iat": 1687171759,
    "exp": 1709290159,
    "authority_hints": [
        "https://trust-anchor.example.org"
      ],
    "jwks": {
        "keys": [
            {
                "kid": "WdQxSaTiwDB3aYuK40v6M2DNqd8eG3bUTtQLKNZUIek",
                "kty": "EC",
                "crv": "P-256",
                "x": "dxqiTS6Rs9t8zKMRjjN1ITEBdcDNGAOjl0SSgeMtrA8",
                "y": "GiOvU_9vAsMRR-CZ1jlTy4FHqjFXVXwHxchPmk-E1Bg"
            }
        ]
    },
    "metadata": {
        "federation_entity": {
            "homepage_uri": "https://eid-provider.wallet.ipzs.it/",
            "organization_name": "Istituto Poligrafico e Zecca dello Stato",
            "contacts": [
                "informazioni@ipzs.it",
                "protocollo@pec.ipzs.it"
            ],
            "tos_uri": "https://eid-provider.wallet.ipzs.it/public/info_policy.html",
            "policy_uri": "https://eid-provider.wallet.ipzs.it/public/privacy_policy.html",
            "logo_uri": "https://eid-provider.wallet.ipzs.it/public/logo.svg"
        },
        "oauth_authorization_server": {
            "issuer": "https://eid-provider.wallet.ipzs.it",
            "pushed_authorization_request_endpoint": "https://eid-provider.wallet.ipzs.it/as/par",
            "authorization_endpoint": "https://eid-provider.wallet.ipzs.it/authorize",
            "token_endpoint": "https://eid-provider.wallet.ipzs.it/token",
            "client_registration_types_supported": [
                "automatic"
            ],
            "code_challenge_methods_supported": [
                "S256"
            ],
            "acr_values_supported": [
                "https://www.spid.gov.it/SpidL2",
                "https://www.spid.gov.it/SpidL3"
            ],
            "scopes_supported": [
                "PersonIdentificationData"
            ],
            "response_modes_supported": [
                "form_post.jwt",
                "query"
            ],
            "grant_types_supported": [
                "authorization_code"
            ],
            "token_endpoint_auth_methods_supported": [
                "attest_jwt_client_auth"
            ],
            "token_endpoint_auth_signing_alg_values_supported": [
                "ES256"
            ],
            "request_object_signing_alg_values_supported": [
                "ES256"
            ],
            "jwks": {
                "keys": [
                    {
                        "kid": "WdQxSaTiwDB3aYuK40v6M2DNqd8eG3bUTtQLKNZUIek",
                        "kty": "EC",
                        "crv": "P-256",
                        "x": "dxqiTS6Rs9t8zKMRjjN1ITEBdcDNGAOjl0SSgeMtrA8",
                        "y": "GiOvU_9vAsMRR-CZ1jlTy4FHqjFXVXwHxchPmk-E1Bg"
                    }
                ]
            }
        },
        "openid_credential_issuer": {
            "credential_issuer": "https://eid-provider.wallet.ipzs.it",
            "credential_endpoint": "https://eid-provider.wallet.ipzs.it/credential",
            "revocation_endpoint": "https://eid-provider.wallet.ipzs.it/revoke",
            "status_attestation_endpoint": "https://eid-provider.wallet.ipzs.it/status",
            "display": [
                {
                    "name": "eID Provider",
                    "locale": "it-IT",
                    "logo": {
                        "url": "https://eid-provider.wallet.ipzs.it/public/logo.svg",
                        "alt_text": "logo eID Provider"
                    }
                },
                {
                    "name": "eID Provider",
                    "locale": "en-US",
                    "logo": {
                        "url": "https://eid-provider.wallet.ipzs.it/public/logo.svg",
                        "alt_text": "eID Provider's logo"
                    }
                }
            ],
            "credential_configurations_supported": {
                "PersonIdentificationData": {
                    "format": "vc+sd-jwt",
                    "scope": "it-wallet",
                    "display": [
                        {
                            "name": "Person Identification Data",
                            "locale": "it-IT"
                        },
                        {
                            "name": "Person Identification Data",
                            "locale": "en-US"
                        }
                    ],
                    "cryptographic_binding_methods_supported": [
                        "jwk"
                    ],
                    "credential_signing_alg_values_supported": [
                        "ES256",
                        "ES384",
                        "ES512"
                    ],
                    "proof_types_supported": {
                        "jwt": {
                            "proof_signing_alg_values_supported": [
                                "ES256",
                                "ES384",
                                "ES512"
                            ]
                        }
                    },
                    "vct": "PersonIdentificationData",
                    "claims": {
                        "given_name": {
                            "value_type": "string",
                            "display": [
                                {
                                    "name": "Nome",
                                    "locale": "it-IT"
                                },
                                {
                                    "name": "First Name",
                                    "locale": "en-US"
                                }
                            ]
                        },
                        "family_name": {
                            "value_type": "string",
                            "display": [
                                {
                                    "name": "Cognome",
                                    "locale": "it-IT"
                                },
                                {
                                    "name": "Family Name",
                                    "locale": "en-US"
                                }
                            ]
                        },
                        "birth_date": {
                            "value_type": "string",
                            "display": [
                                {
                                    "name": "Data di Nascita",
                                    "locale": "it-IT"
                                },
                                {
                                    "name": "Date of Birth",
                                    "locale": "en-US"
                                }
                            ]
                        },
                        "unique_id": {
                            "value_type": "string",
                            "display": [
                                {
                                    "name": "Identificativo univoco",
                                    "locale": "it-IT"
                                },
                                {
                                    "name": "Unique Identifier",
                                    "locale": "en-US"
                                }
                            ]
                        },
                        "tax_id_code": {
                            "value_type": "string",
                            "display": [
                                {
                                    "name": "Codice Fiscale",
                                    "locale": "it-IT"
                                },
                                {
                                    "name": "Tax Id Number",
                                    "locale": "en-US"
                                }
                            ]
                        }
                    }
                }
            },
            "jwks": {
                "keys": [
                    {
                        "kid": "WdQxSaTiwDB3aYuK40v6M2DNqd8eG3bUTtQLKNZUIek",
                        "kty": "EC",
                        "crv": "P-256",
                        "x": "dxqiTS6Rs9t8zKMRjjN1ITEBdcDNGAOjl0SSgeMtrA8",
                        "y": "GiOvU_9vAsMRR-CZ1jlTy4FHqjFXVXwHxchPmk-E1Bg"
                    }
                ]
            }
        }
    }
}

=== it-helpers/it-wallet-helpers/docs/schemes/examples/wp-ec.json
{
    "iss": "https://wallet-provider.example.org",
    "sub": "https://wallet-provider.example.org",
    "iat": 1687171759,
    "exp": 1709290159,
    "authority_hints": [
        "https://trust-anchor.example.org"
      ],
    "jwks": {
        "keys": [
            {
                "kid": "173a0b13ed11366f1c1a09c57201318a",
                "kty": "EC",
                "crv": "P-256",
                "x": "WUJaIdfs0zSahVMNkHwqt_Tka5XVil0AcQH3XLyAimM",
                "y": "WexD__Cr9Ajz8N2yxfEJsOWQXmVRcIfu2Rk16Wzlf70"
            }
        ]
    },
    "metadata": {
        "federation_entity": {
            "homepage_uri": "https://wallet-provider.example.org",
            "organization_name": "IT Wallet Provider",
            "contacts": [
                "informazioni@wallet-provider.example.org"
            ],
            "tos_uri": "https://wallet-provider.example.org/info_policy.html",
            "policy_uri": "https://wallet-provider.example.org/privacy_policy.html",
            "logo_uri": "https://wallet-provider.example.org/logo.svg"
        },
        "wallet_provider": {
            "token_endpoint": "https://wallet-provider.example.org/token",
            "attested_security_context_values_supported": [
                "https://trust-list.eu/aal/basic",
                "https://trust-list.eu/aal/medium",
                "https://trust-list.eu/aal/high"
            ],
            "grant_types_supported": [
                "urn:ietf:params:oauth:client-assertion-type:jwt-client-attestation"
            ],
            "token_endpoint_auth_methods_supported": ["private_key_jwt"],
            "token_endpoint_auth_signing_alg_values_supported": ["ES256"],
            "jwks": {
                "keys": [
                    {
                        "kid": "5t5YYpBhN-EgIEEI5iUzr6r0MR02LnVQ0OmekmNKcjY",
                        "kty": "EC",
                        "crv": "P-256",
                        "x": "qrJrj3Af_B57sbOIRrcBM7br7wOc8ynj7lHFPTeffUk",
                        "y": "1H0cWDyGgvU8w-kPKU_xycOCUNT2o0bwslIQtnPU6iM"
                    }
                ]
            }
        }
    }
}
